/* ============ exporter.js — standalone deck, project files, PDF (spec FR-EXP) ============ */
"use strict";
(function (SF) {
  const { $, el, state, t } = SF;

  /* Because every library/style is inlined in THIS file, the exporter can
     read its own <script>/<style> tags and re-embed them — no duplication,
     no network, ever. */
  const grab = (id) => {
    const node = document.getElementById(id);
    return node ? node.textContent : "";
  };
  /* Belt & suspenders: if generated content ever contained "</script", close-tag-escape it. */
  const scriptSafe = (js) => js.replace(/<\/(script)/gi, "<\\/$1");

  /* ---------- image downscaling (FR-EXP-4) ---------- */
  async function downscaleAsset(asset, maxPx, quality) {
    try {
      const img = new Image();
      await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = `data:${asset.mime};base64,${asset.b64}`; });
      if (Math.max(img.width, img.height) <= maxPx) return asset;
      const scale = maxPx / Math.max(img.width, img.height);
      const canvas = document.createElement("canvas");
      canvas.width = Math.round(img.width * scale);
      canvas.height = Math.round(img.height * scale);
      canvas.getContext("2d").drawImage(img, 0, 0, canvas.width, canvas.height);
      const uri = canvas.toDataURL("image/jpeg", quality || 0.85);
      return { kind: asset.kind, mime: "image/jpeg", b64: uri.split(",")[1] };
    } catch (e) { return asset; }
  }

  /* ---------- deck export (FR-EXP-1) ---------- */
  async function buildDeckHtml(opts) {
    opts = opts || {};
    const o = state.outline;

    let originalAssets = null;
    if (opts.downscale) {
      originalAssets = state.assets;
      const scaled = {};
      for (const [k, v] of Object.entries(state.assets)) scaled[k] = await downscaleAsset(v, 1920, 0.85);
      state.assets = scaled;
    }
    let slidesHtml;
    try {
      const holder = el("div");
      holder.appendChild(SF.render.buildAllSections({ forExport: true, liveCharts: opts.liveCharts }));
      slidesHtml = holder.innerHTML;
    } finally {
      if (originalAssets) state.assets = originalAssets;
    }

    const title = SF.escapeHtml(o.title || "Presentation");
    const version = SF.escapeHtml(state.version);
    const initJs = scriptSafe([
      "var deck = new Reveal({",
      "  width: 1280, height: 720, margin: 0.02, minScale: 0.05, maxScale: 4,",
      "  hash: true, center: false, slideNumber: 'c/t', controls: true, progress: true,",
      "  plugins: [RevealNotes]",
      "});",
      "deck.initialize().then(function () {",
      "  document.querySelector('.reveal-viewport').setAttribute('data-sf-theme', " + JSON.stringify(state.theme) + ");",
      opts.liveCharts ? [
        "  document.querySelectorAll('canvas[data-sf-chart-spec]').forEach(function (cv) {",
        "    try { var spec = JSON.parse(cv.getAttribute('data-sf-chart-spec'));",
        "      new Chart(cv.getContext('2d'), window.__sfChartCfg(spec)); } catch (e) {}",
        "  });",
      ].join("\n") : "",
      "});",
    ].join("\n"));

    /* live-chart config builder is serialized from charts.js (theme-aware) */
    const chartHelper = opts.liveCharts ? scriptSafe(
      "window.__sfChartCfg = function (spec) { return (" + SF.charts.toChartJsConfig.toString() +
      ")(spec, " + JSON.stringify(state.theme) + ", { fontSize: 22 }); };\n" +
      "var THEME_CHART = " + JSON.stringify({
        corporate: { ink: "#16233c", grid: "rgba(22,35,60,.12)", palette: ["#2456d6", "#0e9488", "#d97706", "#7c3aed", "#be185d", "#4d7c0f"] },
        dark: { ink: "#edf0f6", grid: "rgba(237,240,246,.14)", palette: ["#6f9dff", "#4dd0c0", "#ffb454", "#c4a5ff", "#ff8fab", "#a3d977"] },
        contrast: { ink: "#ffffff", grid: "rgba(255,255,255,.28)", palette: ["#ffd400", "#00e5ff", "#ff6ec7", "#7CFC00", "#ff9e00", "#ffffff"] },
      }) + ";") : "";

    return [
      "<!doctype html>",
      `<html lang="${SF.escapeHtml(o.language || "en")}">`,
      "<head>",
      '<meta charset="utf-8">',
      `<!-- Generated by SlideForge Offline v${version} on ${new Date().toISOString()} — fully self-contained, no network access needed or attempted -->`,
      '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:; font-src data:; connect-src \'none\'; form-action \'none\'; base-uri \'none\'">',
      '<meta name="viewport" content="width=device-width, initial-scale=1">',
      `<title>${title}</title>`,
      `<style>${grab("font-css")}</style>`,
      `<style>${grab("vendor-reveal-css")}</style>`,
      `<style>${grab("deck-css")}</style>`,
      "<style>html,body{margin:0;height:100%;background:#000}</style>",
      "</head>",
      "<body>",
      `<div class="reveal"><div class="slides">${slidesHtml}</div></div>`,
      `<script>${scriptSafe(grab("vendor-reveal"))}<\/script>`,
      `<script>${scriptSafe(grab("vendor-reveal-notes"))}<\/script>`,
      opts.liveCharts ? `<script>${scriptSafe(grab("vendor-chart"))}<\/script>` : "",
      chartHelper ? `<script>${chartHelper}<\/script>` : "",
      `<script>${initJs}<\/script>`,
      "</body></html>",
    ].filter(Boolean).join("\n");
  }

  function estimateSize() {
    let n = 3 * 1024 * 1024; // vendored base
    for (const a of Object.values(state.assets)) n += a.b64.length * 0.75;
    return n;
  }

  async function exportDeck() {
    const btn = $("#btn-export-deck");
    btn.disabled = true;
    try {
      const html = await buildDeckHtml({
        liveCharts: $("#exp-live-charts").checked,
        downscale: $("#exp-downscale").checked,
      });
      const safeName = (state.outline.title || "presentation").replace(/[^\wÀ-￿ -]+/g, "").trim().replace(/\s+/g, "-").slice(0, 60) || "presentation";
      SF.downloadFile(safeName + ".html", html, "text/html;charset=utf-8");
      SF.toast(t("ex.done", { size: SF.fmtBytes(html.length) }), "ok", 6000);
    } catch (e) {
      SF.toast(t("ex.failed", { msg: e.message }), "error", 8000);
    } finally { btn.disabled = false; }
  }

  /* ---------- project save / load (FR-EXP-2, §5.2 — tokens NEVER written) ---------- */
  function exportProject() {
    const c = state.config;
    const project = {
      format: "slideforge-project",
      version: 1,
      created: new Date().toISOString(),
      appVersion: state.version,
      outline: state.outline,
      theme: state.theme,
      assets: state.assets,
      gen: state.gen,
      config: { llm_base: c.llmBase, llm_model: c.llmModel, flux_base: c.fluxBase, flux_model: c.fluxModel, image_size: c.imageSize },
    };
    const name = ((state.outline && state.outline.title) || "slideforge-project").replace(/[^\w -]+/g, "").trim().replace(/\s+/g, "-").slice(0, 50);
    SF.downloadFile(name + ".slideforge.json", JSON.stringify(project), "application/json");
  }

  async function importProject(file) {
    try {
      const json = JSON.parse(await file.text());
      if (json.format !== "slideforge-project") throw new Error(t("ex.notProject"));
      /* re-validate + sanitize EVERYTHING (defense against tampered files, §5.2) */
      const outline = SF.schema.validateOutline(json.outline);
      const assets = {};
      const validIds = new Set(outline.slides.map((s) => s.id));
      if (json.assets && typeof json.assets === "object") {
        for (const [id, a] of Object.entries(json.assets)) {
          if (!validIds.has(id) || !a || typeof a.b64 !== "string") continue;
          if (!/^[A-Za-z0-9+/=\s]+$/.test(a.b64)) continue;
          const mime = ["image/png", "image/jpeg", "image/webp"].includes(a.mime) ? a.mime : "image/png";
          assets[id] = { kind: a.kind === "user_image" ? "user_image" : "image", mime, b64: a.b64.replace(/\s+/g, "") };
        }
      }
      state.outline = outline;
      state.assets = assets;
      state.theme = ["corporate", "dark", "contrast"].includes(json.theme) ? json.theme : "corporate";
      if (json.config && typeof json.config === "object") {
        const c = state.config;
        if (!c.llmBase && json.config.llm_base) c.llmBase = SF.cleanText(json.config.llm_base, 300);
        if (!c.llmModel && json.config.llm_model) c.llmModel = SF.cleanText(json.config.llm_model, 100);
        if (!c.fluxBase && json.config.flux_base) c.fluxBase = SF.cleanText(json.config.flux_base, 300);
        SF.config.fillForm();
      }
      state.approved = true;
      SF.history.resetHistory();
      $("#theme-select").value = state.theme;
      SF.emit("outline-replaced");
      SF.emit("theme-changed");
      SF.toast(t("ex.projLoaded", { n: outline.slides.length }), "ok");
      $("#dlg-export").close();
      SF.app.updateUI();
    } catch (e) {
      SF.toast(t("ex.projBad", { msg: e.message }), "error", 8000);
    }
  }

  /* ---------- PDF via browser print (FR-EXP-3) ---------- */
  function printPdf() {
    const root = $("#print-root");
    root.textContent = "";
    const holder = el("div", { class: "sf-themed", "data-sf-theme": state.theme });
    const frag = SF.render.buildAllSections({ forExport: true });
    for (const sec of Array.from(frag.children)) {
      const page = el("div", { class: "print-slide sf-themed reveal", "data-sf-theme": state.theme });
      sec.style.display = "block";
      page.appendChild(sec);
      holder.appendChild(page);
    }
    root.appendChild(holder);
    window.print();
    setTimeout(() => (root.textContent = ""), 2000);
  }

  function updateSizeWarning() {
    const warnBox = $("#exp-size-warning");
    const est = estimateSize();
    if (est > 50 * 1024 * 1024) {
      warnBox.hidden = false;
      warnBox.textContent = t("ex.sizeWarn", { size: SF.fmtBytes(est) });
      $("#exp-downscale").checked = true;
    } else warnBox.hidden = true;
  }

  function openDialog() {
    updateSizeWarning();
    const dlg = $("#dlg-export");
    if (!dlg.open) dlg.showModal();
  }

  function init() {
    $("#btn-export-deck").addEventListener("click", exportDeck);
    $("#btn-export-project").addEventListener("click", exportProject);
    $("#project-input").addEventListener("change", (e) => { if (e.target.files[0]) importProject(e.target.files[0]); });
    $("#btn-print-pdf").addEventListener("click", printPdf);
  }

  SF.exporter = { init, exportDeck, exportProject, importProject, printPdf, updateSizeWarning, buildDeckHtml, openDialog };
})(window.SF);
